### ISSUE TITLE
老兄你的qq群怎么搜不到啊？？？？

### ISSUE THREAD

**Issue by haodedog** [longlonger2022/Disk-Squeezer#4]
![PixPin_2024-08-08_16-11-50](https://github.com/user-attachments/assets/7af26d42-9afd-49ab-9ee0-25471c19c68e)

**Comment by 0xlonger** [comment]
> ![PixPin_2024-08-08_16-11-50](https://private-user-images.githubusercontent.com/117104416/356138142-7af26d42-9afd-49ab-9ee0-25471c19c68e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjA5MzgsIm5iZiI6MTcyMzEyMDYzOCwicGF0aCI6Ii8xMTcxMDQ0MTYvMzU2MTM4MTQyLTdhZjI2ZDQyLTlhZmQtNDlhYi05ZWUwLTI1NDcxYzE5YzY4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMjM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTQ5ZjE1NzFhYzYyNWI0ZWQzNTRiOWFmZTk1NGJmN2EzMmY4MzliMDhkNWQ0MGFmMzRlZDFhYjliOTJjZjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.14H9lSjc9aOy0jH-jfzIlNhAbXkIyYfZ63nrF9g0-LI)

试试这个链接(doge ：[龙ger_longer·交流群](https://qm.qq.com/cgi-bin/qm/qr?k=VQaeH39u4LrFakGm_uw3US05GTftVFVk&jump_from=webapi&authKey=8zOXBtvNZYjRuYcrAWnSeTwTzkBZGItKDVhESFhOXhaP3zu8CYUB9D4ENUMSzhxm)
